name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out"
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.REGISTRY_TOKEN}}
      - name: Build image
        run: |
          docker build . -t ghcr.io/moedevelops/chatding:latest -t ghcr.io/moedevelops/chatding:${{github.event.release.tag_name}}
          docker push ghcr.io/moedevelops/chatding:latest
          docker push ghcr.io/moedevelops/chatding:${{github.event.release.tag_name}}
